
#type: args

train:
  epochs: 200
  batch_size: 256
  lr: 0.0001

diffusion:
  layers: 4
  channels: 128 
  nheads: 8
  diffusion_embedding_dim: 2
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 24
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 256
  featureemb: 64
  target_strategy: "test"
