
#type: args

train:
  epochs: 400
  batch_size: 256 
  lr: 0.0005

diffusion:
  layers: 12
  channels: 1024
  nheads: 16
  diffusion_embedding_dim: 1024
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 512
  featureemb: 256
  target_strategy: "test"
