
#type: args

train:
  epochs: 400
  batch_size: 256 
  lr: 0.0005

diffusion:
  layers: 6 
  channels: 512 
  nheads: 8
  diffusion_embedding_dim: 512
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 20
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 512
  featureemb: 256
  target_strategy: "test"
